version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2999:2999"
    depends_on:
      - mariadb
#    volumes:
#      - .:/usr/app

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: databaseName
      MYSQL_USER: username
      MYSQL_PASSWORD: userPassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: